# Generated by Django 4.1.7 on 2023-08-04 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviewapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 - Trash"),
                    (2, "2 - Too bad"),
                    (3, "3 - Terrible"),
                    (4, "4 - Bad"),
                    (5, "5 - OK"),
                    (6, "6 - Watchable"),
                    (7, "7 - Good"),
                    (8, "8 - Very Good"),
                    (9, "9 - Perfect"),
                    (10, "10 - Master Piece"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name="CommentOnReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("body", models.TextField(max_length=2000)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reviewapp.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
