# Generated by Django 4.1.7 on 2023-08-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewapp", "0003_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(
                blank=True,
                default="I don't want to leave a comment but just rate",
                max_length=2000,
            ),
        ),
    ]
