# Generated by Django 4.1.7 on 2023-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewapp", "0004_alter_review_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(
                blank=True,
                default="this user did not leave a review but just rate",
                max_length=2000,
            ),
        ),
    ]
