# Generated by Django 4.1.7 on 2023-08-02 17:44

import authapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movieapp", "0002_alter_movie_released_alter_movie_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        default="img/no_avatar.jpg",
                        null=True,
                        upload_to='profile_images',
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile_info",
                    models.TextField(blank=True, max_length=150, null=True),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "to_watch",
                    models.ManyToManyField(related_name="towatch", to="movieapp.movie"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watched",
                    models.ManyToManyField(related_name="watched", to="movieapp.movie"),
                ),
            ],
        ),
    ]
