# Generated by Django 4.1.7 on 2023-08-03 16:17

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="created",
            new_name="date_created",
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="default_avatar.jpg",
                null=True,
                upload_to='profile_images',
            ),
        ),
    ]
