# Generated by Django 4.1.7 on 2023-08-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actorname", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genrename", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=30)),
                ("rating", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150)),
                ("Year", models.DateField(blank=True)),
                ("Rated", models.CharField(blank=True, max_length=10)),
                ("Released", models.DateField(blank=True)),
                ("Runtime", models.CharField(blank=True, max_length=20)),
                ("Director", models.CharField(blank=True, max_length=70)),
                ("Writer", models.CharField(blank=True, max_length=200)),
                ("Plot", models.TextField(blank=True, max_length=900)),
                ("Language", models.CharField(blank=True, max_length=100)),
                ("Poster", models.ImageField(blank=True, upload_to="movies")),
                ("Poster_url", models.URLField(blank=True)),
                ("imdbID", models.CharField(blank=True, max_length=50)),
                ("Type", models.CharField(blank=True, max_length=10)),
                ("Actors", models.ManyToManyField(blank=True, to="movieapp.actor")),
                ("Genre", models.ManyToManyField(blank=True, to="movieapp.genre")),
                ("Ratings", models.ManyToManyField(blank=True, to="movieapp.rating")),
            ],
        ),
    ]
