# Generated by Django 4.1.7 on 2023-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Released",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Year",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
